/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppLibraryRouteImport } from './routes/_app.library'
import { Route as AppReviewRouteImport } from './routes/_app.review'
import { Route as AppSearchRouteImport } from './routes/_app.search'
import { Route as AppPapersIdRouteImport } from './routes/_app.papers.$id'
import { Route as AppWorkflowIndexRouteImport } from './routes/_app.workflow.index'
import { Route as AppWorkflowIdRouteImport } from './routes/_app.workflow.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewRoute = AppReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppPapersIdRoute = AppPapersIdRouteImport.update({
  id: '/papers/$id',
  path: '/papers/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkflowIndexRoute = AppWorkflowIndexRouteImport.update({
  id: '/workflow/',
  path: '/workflow/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkflowIdRoute = AppWorkflowIdRouteImport.update({
  id: '/workflow/$id',
  path: '/workflow/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/library': typeof AppLibraryRoute
  '/review': typeof AppReviewRoute
  '/search': typeof AppSearchRoute
  '/papers/$id': typeof AppPapersIdRoute
  '/workflow/$id': typeof AppWorkflowIdRoute
  '/workflow/': typeof AppWorkflowIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/library': typeof AppLibraryRoute
  '/review': typeof AppReviewRoute
  '/search': typeof AppSearchRoute
  '/papers/$id': typeof AppPapersIdRoute
  '/workflow/$id': typeof AppWorkflowIdRoute
  '/workflow': typeof AppWorkflowIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/library': typeof AppLibraryRoute
  '/_app/review': typeof AppReviewRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/papers/$id': typeof AppPapersIdRoute
  '/_app/workflow/$id': typeof AppWorkflowIdRoute
  '/_app/workflow/': typeof AppWorkflowIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/library'
    | '/review'
    | '/search'
    | '/papers/$id'
    | '/workflow/$id'
    | '/workflow/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/library'
    | '/review'
    | '/search'
    | '/papers/$id'
    | '/workflow/$id'
    | '/workflow'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/library'
    | '/_app/review'
    | '/_app/search'
    | '/_app/papers/$id'
    | '/_app/workflow/$id'
    | '/_app/workflow/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/review': {
      id: '/_app/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AppReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/papers/$id': {
      id: '/_app/papers/$id'
      path: '/papers/$id'
      fullPath: '/papers/$id'
      preLoaderRoute: typeof AppPapersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workflow/': {
      id: '/_app/workflow/'
      path: '/workflow'
      fullPath: '/workflow/'
      preLoaderRoute: typeof AppWorkflowIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workflow/$id': {
      id: '/_app/workflow/$id'
      path: '/workflow/$id'
      fullPath: '/workflow/$id'
      preLoaderRoute: typeof AppWorkflowIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppLibraryRoute: typeof AppLibraryRoute
  AppReviewRoute: typeof AppReviewRoute
  AppSearchRoute: typeof AppSearchRoute
  AppPapersIdRoute: typeof AppPapersIdRoute
  AppWorkflowIdRoute: typeof AppWorkflowIdRoute
  AppWorkflowIndexRoute: typeof AppWorkflowIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppLibraryRoute: AppLibraryRoute,
  AppReviewRoute: AppReviewRoute,
  AppSearchRoute: AppSearchRoute,
  AppPapersIdRoute: AppPapersIdRoute,
  AppWorkflowIdRoute: AppWorkflowIdRoute,
  AppWorkflowIndexRoute: AppWorkflowIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
