"""sprint4_add_papers_table

Revision ID: 4836e1df5130
Revises: c1c06fba543e
Create Date: 2026-08-14 10:36:40.800855

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4836e1df5130'
down_revision: Union[str, None] = 'c1c06fba543e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('papers',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=False),
    sa.Column('authors', sa.Text(), nullable=False, comment='JSON-encoded list of author name strings'),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('journal', sa.String(length=200), nullable=False),
    sa.Column('citations', sa.Integer(), nullable=False),
    sa.Column('doi', sa.String(length=200), nullable=False),
    sa.Column('pdf_url', sa.Text(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=False, comment='JSON-encoded list of tag strings'),
    sa.Column('first_saved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('papers')
    # ### end Alembic commands ###