import type { Paper } from "@/lib/mock-data";
import { buildAgentReply } from "@/lib/agent";

export type PlanStep = { label: string; detail: string; ms: number };

export type AgentRun = {
  steps: PlanStep[];
  /** Produced once every step has finished. */
  finish: () => { text: string; artifact?: Artifact };
};

export type Artifact =
  | { type: "workspace"; id: string; name: string; count: number }
  | { type: "document"; id: string; title: string; kind: string };

export const DOC_KINDS = [
  "Literature review",
  "Summary",
  "Report",
  "Outline",
  "Brief",
] as const;

export function detectIntent(text: string): "workspace" | "document" | "answer" {
  const q = text.toLowerCase();
  if (q.includes("workspace") || q.includes("collection") || q.includes("save these"))
    return "workspace";
  if (q.includes("document") || q.includes("write up") || q.includes("draft a") || q.includes("generate a doc"))
    return "document";
  return "answer";
}

export function searchSteps(query: string, n: number): PlanStep[] {
  return [
    { label: "Understanding request", detail: `Parsing intent for "${truncate(query)}"`, ms: 700 },
    { label: "Scanning corpus", detail: "81.4M records · arXiv, bioRxiv, S2ORC", ms: 900 },
    { label: "Dense retrieval", detail: "SPECTER2 embeddings · top-500 candidates", ms: 900 },
    { label: "Citation graph expansion", detail: "PageRank walk · +214 neighbours", ms: 800 },
    { label: "Reranking with critic", detail: "Cross-encoder · nDCG 0.91", ms: 850 },
    { label: "Verifying claims", detail: `Retraction check · ${n} papers cleared`, ms: 700 },
  ];
}

export function workspaceSteps(query: string, n: number): PlanStep[] {
  return [
    { label: "Reading your request", detail: "Task: curate papers → create workspace", ms: 600 },
    { label: "Scoring relevance", detail: `Ranking ${n} candidates against "${truncate(query)}"`, ms: 850 },
    { label: "Filtering low-signal papers", detail: "Dropping match < 45% and retracted work", ms: 750 },
    { label: "Creating workspace", detail: "Allocating scoped agent memory", ms: 700 },
    { label: "Attaching papers", detail: "Indexing full texts for scoped reasoning", ms: 750 },
  ];
}

export function documentSteps(kind: string, n: number): PlanStep[] {
  return [
    { label: "Planning document", detail: `Outlining a ${kind.toLowerCase()}`, ms: 650 },
    { label: "Reading papers in scope", detail: `${n} papers · extracting claims`, ms: 900 },
    { label: "Clustering findings", detail: "Grouping by method, dataset, result", ms: 800 },
    { label: "Drafting sections", detail: "Composing narrative with citations", ms: 950 },
    { label: "Fact-checking", detail: "Cross-referencing every cited claim", ms: 750 },
  ];
}

export function answerSteps(n: number): PlanStep[] {
  return [
    { label: "Interpreting question", detail: "Mapping to scoped corpus", ms: 550 },
    { label: "Reading papers", detail: `${n} papers in scope`, ms: 800 },
    { label: "Synthesizing answer", detail: "Composing grounded response", ms: 750 },
  ];
}

function truncate(s: string, n = 42) {
  return s.length > n ? `${s.slice(0, n)}…` : s;
}

export function buildDocument(
  prompt: string,
  kind: string,
  papers: Paper[],
  scope: string,
): { title: string; content: string } {
  const clean = prompt.replace(/^(generate|create|write|draft)\s+(a|an|the)?\s*/i, "").trim();
  const title = capitalize(clean || `${kind} — ${scope.replace(/"/g, "")}`).slice(0, 70);
  const years = papers.map((p) => p.year);
  const span = papers.length ? `${Math.min(...years)}–${Math.max(...years)}` : "n/a";

  const content = [
    `# ${title}`,
    `_${kind} · ${papers.length} papers · ${span} · generated by Arclight_`,
    `## Abstract`,
    `This ${kind.toLowerCase()} synthesizes ${papers.length} papers in ${scope}. It consolidates methodological trends, reported gains, and open problems, and highlights where the evidence base is thin.`,
    buildAgentReply("summarize corpus", papers, scope),
    buildAgentReply("write literature review", papers, scope),
    buildAgentReply("find research gaps", papers, scope),
    buildAgentReply("compare methodologies", papers, scope),
    `## Bibliography\n` +
      papers
        .map(
          (p, i) =>
            `${i + 1}. ${p.authors.join(", ")} (${p.year}). *${p.title}*. ${p.journal}. ${p.citations} citations.`,
        )
        .join("\n"),
  ].join("\n\n");

  return { title, content };
}

function capitalize(s: string) {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

/** Sprint 7 — step labels for the real LangGraph agent. Order matches the
 *  actual node sequence in backend/app/agents/graph.py, so liveIndex from
 *  SSE "step" events lines up with what's shown here. */
export function gapAgentSteps(n: number): PlanStep[] {
  return [
    { label: "Reading papers in scope", detail: `${n} papers`, ms: 0 },
    { label: "Scoring relevance", detail: "Ranking against your question", ms: 0 },
    { label: "Clustering findings", detail: "Grouping by theme", ms: 0 },
    { label: "Synthesizing summary", detail: "Reading across the corpus", ms: 0 },
    { label: "Identifying research gaps", detail: "Grounded in what's actually missing", ms: 0 },
    { label: "Finalizing response", detail: "Composing the report", ms: 0 },
  ];
}

export function litReviewAgentSteps(n: number): PlanStep[] {
  return [
    { label: "Reading papers in scope", detail: `${n} papers`, ms: 0 },
    { label: "Scoring relevance", detail: "Ranking against your question", ms: 0 },
    { label: "Clustering findings", detail: "Grouping by theme", ms: 0 },
    { label: "Synthesizing summary", detail: "Reading across the corpus", ms: 0 },
    { label: "Identifying research gaps", detail: "Grounded in what's actually missing", ms: 0 },
    { label: "Drafting narrative", detail: "Writing the literature review", ms: 0 },
    { label: "Finalizing response", detail: "Composing the report", ms: 0 },
  ];
}

export function genericAgentSteps(n: number): PlanStep[] {
  return [
    { label: "Reading papers in scope", detail: `${n} papers`, ms: 0 },
    { label: "Scoring relevance", detail: "Ranking against your question", ms: 0 },
    { label: "Clustering findings", detail: "Grouping by theme", ms: 0 },
    { label: "Synthesizing summary", detail: "Reading across the corpus", ms: 0 },
    { label: "Finalizing response", detail: "Composing the report", ms: 0 },
  ];
}