import { useCallback, useEffect, useRef, useState } from "react";
import { apiFetch } from "@/lib/api";

export type DocStatus = "pending" | "processing" | "done" | "failed";

export type Doc = {
  id: string;
  workspaceId: string;
  title: string;
  kind: "Report" | "Literature review" | "Summary" | "Outline" | "Brief";
  prompt: string;
  content: string;
  createdAt: number;
  words: number;
  status: DocStatus;
  error?: string | null;
};

export type BackendDoc = {
  id: string;
  workspace_id: string;
  title: string;
  kind: Doc["kind"];
  prompt: string;
  content: string;
  created_at: string;
  words: number;
  status: DocStatus;
  error?: string | null;
};

function mapDoc(raw: BackendDoc): Doc {
  return {
    id: raw.id,
    workspaceId: raw.workspace_id,
    title: raw.title,
    kind: raw.kind,
    prompt: raw.prompt,
    content: raw.content,
    createdAt: new Date(raw.created_at).getTime(),
    words: raw.words,
    status: raw.status,
    error: raw.error,
  };
}

/**
 * Sprint 8 — documents now live in Postgres, generated by a Celery worker.
 * This hook fetches the real list for a workspace and polls while any
 * document is still pending/processing, so a generation started before the
 * tab was closed shows up finished on reopen.
 */
export function useDocuments(workspaceId?: string) {
  const [docs, setDocs] = useState<Doc[]>([]);
  const pollRef = useRef<ReturnType<typeof setInterval> | null>(null);

  const refresh = useCallback(async () => {
    if (!workspaceId) return;
    try {
      const raw = await apiFetch<BackendDoc[]>(`/workspaces/${workspaceId}/documents`);
      setDocs(raw.map(mapDoc));
    } catch (err) {
      console.error("Failed to load documents:", err);
    }
  }, [workspaceId]);

  useEffect(() => {
    refresh();
  }, [refresh]);

  useEffect(() => {
    const hasInFlight = docs.some((d) => d.status === "pending" || d.status === "processing");
    if (!hasInFlight) {
      if (pollRef.current) clearInterval(pollRef.current);
      pollRef.current = null;
      return;
    }
    if (pollRef.current) return;
    pollRef.current = setInterval(refresh, 2000);
    return () => {
      if (pollRef.current) clearInterval(pollRef.current);
      pollRef.current = null;
    };
  }, [docs, refresh]);

  const create = useCallback(
    async (doc: {
      workspaceId: string;
      title: string;
      kind: Doc["kind"];
      prompt: string;
    }): Promise<Doc> => {
      const raw = await apiFetch<BackendDoc>("/documents", {
        method: "POST",
        body: JSON.stringify({
          workspace_id: doc.workspaceId,
          title: doc.title,
          kind: doc.kind,
          prompt: doc.prompt,
        }),
      });
      const mapped = mapDoc(raw);
      setDocs((prev) => [mapped, ...prev]);
      return mapped;
    },
    [],
  );

  const remove = useCallback(
    async (id: string) => {
      setDocs((prev) => prev.filter((d) => d.id !== id));
      try {
        await apiFetch(`/documents/${id}`, { method: "DELETE" });
      } catch (err) {
        console.error("Failed to delete document:", err);
        refresh();
      }
    },
    [refresh],
  );

  return { docs, create, remove, refresh };
}
