import type { Paper } from "@/lib/mock-data";

export function downloadText(filename: string, text: string, mime = "text/markdown") {
  const blob = new Blob([text], { type: `${mime};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export function slugify(s: string) {
  return (
    s
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 48) || "arclight"
  );
}

export function stamp() {
  return new Date().toISOString().slice(0, 10);
}

/**
 * Generate a BibTeX citation key from author and title
 * Example: Vaswani et al. (2017) "Attention is..." -> vaswani2017attention
 */
export function generateBibtexKey(paper: Paper): string {
  const author =
    (paper.authors[0] || "anon")
      .split(/\s+/)
      .pop()
      ?.toLowerCase()
      .replace(/[^a-z]/g, "") || "author";
  const year = paper.year || new Date().getFullYear();
  const titleWord =
    paper.title
      .split(/\s+/)
      .find((w) => w.length > 3)
      ?.toLowerCase()
      .replace(/[^a-z]/g, "") || "paper";
  return `${author}${year}${titleWord}`;
}

/**
 * Convert a list of papers into standard BibTeX (.bib) format
 */
export function toBibTeX(papers: Paper[]): string {
  if (!papers || papers.length === 0) {
    return "% No papers provided for BibTeX export\n";
  }

  const entries = papers.map((p) => {
    const key = generateBibtexKey(p);
    const authors = p.authors.length > 0 ? p.authors.join(" and ") : "Anonymous";
    const journal = p.journal || "arXiv preprint";
    const fields = [
      `  author    = {${authors}}`,
      `  title     = {{${p.title}}}`,
      `  journal   = {${journal}}`,
      `  year      = {${p.year}}`,
    ];

    if (p.doi) {
      fields.push(`  doi       = {${p.doi}}`);
    }
    if (p.pdfUrl) {
      fields.push(`  url       = {${p.pdfUrl}}`);
    }
    if (p.abstract) {
      const cleanAbstract = p.abstract.replace(/[{}]/g, "").slice(0, 500);
      fields.push(`  abstract  = {${cleanAbstract}...}`);
    }

    return `@article{${key},\n${fields.join(",\n")}\n}`;
  });

  return (
    `% BibTeX export generated by Arclight AI Research Copilot on ${new Date().toISOString()}\n` +
    `% Total papers: ${papers.length}\n\n` +
    entries.join("\n\n") +
    "\n"
  );
}

/**
 * Convert Markdown text into a clean LaTeX (.tex) article source
 */
export function toLaTeX(title: string, markdown: string, papers: Paper[] = []): string {
  // Convert Markdown headings to LaTeX sections
  let body = markdown
    .replace(/^### (.*$)/gim, "\\subsubsection{$1}")
    .replace(/^## (.*$)/gim, "\\subsection{$1}")
    .replace(/^# (.*$)/gim, "\\section{$1}");

  // Bold & Italic formatting
  body = body.replace(/\*\*(.*?)\*\*/g, "\\textbf{$1}").replace(/\*(.*?)\*/g, "\\textit{$1}");

  // Escape special LaTeX characters (outside of commands)
  body = body.replace(/&/g, "\\&").replace(/%/g, "\\%").replace(/\$/g, "\\$").replace(/_/g, "\\_");

  // Format list items
  const lines = body.split("\n");
  const processedLines: string[] = [];
  let inItemize = false;

  for (const line of lines) {
    if (line.trim().startsWith("- ") || line.trim().startsWith("* ")) {
      if (!inItemize) {
        processedLines.push("\\begin{itemize}");
        inItemize = true;
      }
      processedLines.push(`  \\item ${line.trim().slice(2)}`);
    } else {
      if (inItemize) {
        processedLines.push("\\end{itemize}");
        inItemize = false;
      }
      processedLines.push(line);
    }
  }
  if (inItemize) processedLines.push("\\end{itemize}");
  body = processedLines.join("\n");

  const bibtexSection =
    papers.length > 0
      ? `\n\n\\section*{References}\n\\begin{enumerate}\n` +
        papers
          .map(
            (p, i) =>
              `  \\item \\textbf{${p.title}} -- ${p.authors.join(", ")} (${p.year}). \\textit{${p.journal || "ArXiv"}}.`,
          )
          .join("\n") +
        `\n\\end{enumerate}`
      : "";

  return `\\documentclass[11pt,a4paper]{article}
\\usepackage[utf8]{inputenc}
\\usepackage{amsmath,amssymb}
\\usepackage{hyperref}
\\usepackage{booktabs}
\\usepackage{geometry}
\\geometry{margin=1in}

\\title{${title}}
\\author{Arclight AI Research Copilot}
\\date{\\today}

\\begin{document}
\\maketitle

${body}
${bibtexSection}

\\end{document}
`;
}

/**
 * Generate a printable standalone HTML document for 1-click Print to PDF
 */
export function toPrintableHTML(title: string, markdown: string): string {
  // Simple markdown to HTML line conversions
  const htmlContent = markdown
    .replace(/^### (.*$)/gim, '<h3 class="text-base font-semibold mt-4 mb-2 text-gray-800">$1</h3>')
    .replace(
      /^## (.*$)/gim,
      '<h2 class="text-lg font-bold mt-6 mb-3 text-gray-900 border-b pb-1">$1</h2>',
    )
    .replace(
      /^# (.*$)/gim,
      '<h1 class="text-2xl font-bold mt-8 mb-4 text-gray-950 border-b-2 pb-2">$1</h1>',
    )
    .replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.*?)\*/g, "<em>$1</em>")
    .replace(
      /`([^`]+)`/g,
      '<code class="bg-gray-100 px-1 py-0.5 rounded text-xs font-mono">$1</code>',
    )
    .replace(/\n\n/g, '</p><p class="my-2.5 leading-relaxed text-gray-700">');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${title} · Arclight Export</title>
  <style>
    @media print {
      body { margin: 0; padding: 20mm; font-size: 11pt; color: #111; }
      .no-print { display: none !important; }
      h1, h2, h3 { page-break-after: avoid; }
      table { page-break-inside: avoid; }
    }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
      max-width: 800px;
      margin: 40px auto;
      padding: 0 24px;
      color: #222;
      line-height: 1.6;
    }
    h1 { font-size: 26px; border-bottom: 2px solid #eaeaea; padding-bottom: 8px; margin-top: 24px; }
    h2 { font-size: 19px; border-bottom: 1px solid #eaeaea; padding-bottom: 6px; margin-top: 24px; }
    h3 { font-size: 15px; margin-top: 18px; }
    table { width: 100%; border-collapse: collapse; margin: 16px 0; font-size: 13px; }
    th, td { border: 1px solid #ddd; padding: 8px 12px; text-align: left; }
    th { background: #f8f9fa; font-weight: 600; }
    tr:nth-child(even) { background: #fbfbfb; }
    code { font-family: monospace; background: #f4f4f4; padding: 2px 4px; border-radius: 3px; font-size: 85%; }
    .header-bar { display: flex; justify-content: space-between; align-items: center; margin-bottom: 24px; border-bottom: 1px solid #eee; padding-bottom: 12px; }
    .badge { font-size: 11px; background: #eef2ff; color: #4338ca; padding: 3px 8px; border-radius: 9999px; font-weight: 500; }
    .print-btn { background: #18181b; color: #fff; border: none; padding: 8px 16px; border-radius: 6px; font-size: 13px; cursor: pointer; }
    .print-btn:hover { background: #27272a; }
  </style>
</head>
<body>
  <div class="header-bar no-print">
    <span class="badge">Arclight AI Research Copilot</span>
    <button class="print-btn" onclick="window.print()">🖨️ Print / Save as PDF</button>
  </div>
  <article>
    <h1>${title}</h1>
    <p class="my-2.5 leading-relaxed text-gray-700">${htmlContent}</p>
  </article>
</body>
</html>`;
}
